In [2]:
%pip install kagglehub

WARNING: Ignoring invalid distribution ~umpy (/Users/ogechukwuezenwa/miniforge3/lib/python3.12/site-packages)
WARNING: Ignoring invalid distribution ~umpy (/Users/ogechukwuezenwa/miniforge3/lib/python3.12/site-packages)
Collecting kagglehub
  Downloading kagglehub-1.0.2-py3-none-any.whl.metadata (40 kB)
Collecting kagglesdk<1.0,>=0.1.22 (from kagglehub)
  Downloading kagglesdk-0.1.37-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in /Users/ogechukwuezenwa/miniforge3/lib/python3.12/site-packages (from kagglehub) (26.0)
Requirement already satisfied: pyyaml in /Users/ogechukwuezenwa/miniforge3/lib/python3.12/site-packages (from kagglehub) (6.0.2)
Requirement already satisfied: requests in /Users/ogechukwuezenwa/miniforge3/lib/python3.12/site-packages (from kagglehub) (2.33.1)
Requirement already satisfied: tqdm in /Users/ogechukwuezenwa/miniforge3/lib/python3.12/site-packages (from kagglehub) (4.67.1)
Requirement already satisfied: protobuf in /Users/ogechukwuezenwa/miniforge3/lib/python3.12/site-packages (from kagglesdk<1.0,>=0.1.22->kagglehub) (5.29.5)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/ogechukwuezenwa/miniforge3/lib/python3.12/site-packages (from requests->kagglehub) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /Users/ogechukwuezenwa/miniforge3/lib/python3.12/site-packages (from requests->kagglehub) (3.10)
Requirement already satisfied: urllib3<3,>=1.26 in /Users/ogechukwuezenwa/miniforge3/lib/python3.12/site-packages (from requests->kagglehub) (2.5.0)
Requirement already satisfied: certifi>=2023.5.7 in /Users/ogechukwuezenwa/miniforge3/lib/python3.12/site-packages (from requests->kagglehub) (2026.2.25)
Downloading kagglehub-1.0.2-py3-none-any.whl (70 kB)
Downloading kagglesdk-0.1.37-py3-none-any.whl (262 kB)
WARNING: Ignoring invalid distribution ~umpy (/Users/ogechukwuezenwa/miniforge3/lib/python3.12/site-packages)
Installing collected packages: kagglesdk, kagglehub
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [kagglehub]
WARNING: Ignoring invalid distribution ~umpy (/Users/ogechukwuezenwa/miniforge3/lib/python3.12/site-packages)
Successfully installed kagglehub-1.0.2 kagglesdk-0.1.37
WARNING: Ignoring invalid distribution ~umpy (/Users/ogechukwuezenwa/miniforge3/lib/python3.12/site-packages)
WARNING: Ignoring invalid distribution ~umpy (/Users/ogechukwuezenwa/miniforge3/lib/python3.12/site-packages)

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

## Download the dataset

In [17]:
import kagglehub

# Download the latest version of the Telco Customer Churn dataset
path = kagglehub.dataset_download("blastchar/telco-customer-churn")

print("Path to dataset files:", path)

Path to dataset files: /Users/ogechukwuezenwa/.cache/kagglehub/datasets/blastchar/telco-customer-churn/versions/1

In [18]:
import pandas as pd
import os

# See what files were downloaded
print(os.listdir(path))

['WA_Fn-UseC_-Telco-Customer-Churn.csv']

## Explore and clean the dataset

In [ ]:
# display the table
df = pd.read_csv(os.path.join(path, "WA_Fn-UseC_-Telco-Customer-Churn.csv"))

df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [ ]:
# inspect the table to check for the number of columns and rows
print("Shape:", df.shape)
df.info()

Shape: (7043, 21)
<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.9 MB

In [ ]:
# check for missing values
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [20]:
# check for duplicated values
df.duplicated().sum()

np.int64(0)

In [12]:
# clean total charges and check for missing values
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")
df["TotalCharges"].isna().sum()

np.int64(11)

In [13]:
df[df["TotalCharges"].isna()]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,NaN,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,NaN,No
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,...,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,NaN,No
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,NaN,No
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,NaN,No
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,NaN,No
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,NaN,No
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,NaN,No
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,NaN,No
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,NaN,No
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,NaN,No

In [15]:
# remove the 11 missing rows
df = df.dropna(subset=["TotalCharges"])
df["TotalCharges"].isna().sum()

np.int64(0)

In [16]:
# verify the number of rows after cleaning
df["TotalCharges"].isna().sum()

np.int64(0)

In [ ]:
# check for unique values since we have a lot of duplicated values
for column in df.columns:
    print(f"\n{column}:")
    print(df[column].unique())

customerID:
<ArrowStringArray>
['7590-VHVEG', '5575-GNVDE', '3668-QPYBK', '7795-CFOCW', '9237-HQITU',
 '9305-CDSKC', '1452-KIOVK', '6713-OKOMC', '7892-POOKP', '6388-TABGU',
 ...
 '9767-FFLEM', '0639-TSIQW', '8456-QDAVC', '7750-EYXWZ', '2569-WGERO',
 '6840-RESVB', '2234-XADUH', '4801-JZAZL', '8361-LTMKD', '3186-AJIEK']
Length: 7032, dtype: str

gender:
<ArrowStringArray>
['Female', 'Male']
Length: 2, dtype: str

SeniorCitizen:
[0 1]

Partner:
<ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str

Dependents:
<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

tenure:
[ 1 34  2 45  8 22 10 28 62 13 16 58 49 25 69 52 71 21 12 30 47 72 17 27
  5 46 11 70 63 43 15 60 18 66  9  3 31 50 64 56  7 42 35 48 29 65 38 68
 32 55 37 36 41  6  4 33 67 23 57 61 14 20 53 40 59 24 44 19 54 51 26 39]

PhoneService:
<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

MultipleLines:
<ArrowStringArray>
['No phone service', 'No', 'Yes']
Length: 3, dtype: str

InternetService:
<ArrowStringArray>
['DSL', 'Fiber optic', 'No']
Length: 3, dtype: str

OnlineSecurity:
<ArrowStringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

OnlineBackup:
<ArrowStringArray>
['Yes', 'No', 'No internet service']
Length: 3, dtype: str

DeviceProtection:
<ArrowStringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

TechSupport:
<ArrowStringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

StreamingTV:
<ArrowStringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

StreamingMovies:
<ArrowStringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

Contract:
<ArrowStringArray>
['Month-to-month', 'One year', 'Two year']
Length: 3, dtype: str

PaperlessBilling:
<ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str

PaymentMethod:
<ArrowStringArray>
[         'Electronic check',              'Mailed check',
 'Bank transfer (automatic)',   'Credit card (automatic)']
Length: 4, dtype: str

MonthlyCharges:
[29.85 56.95 53.85 ... 63.1  44.2  78.7 ]

TotalCharges:
[  29.85 1889.5   108.15 ...  346.45  306.6  6844.5 ]

Churn:
<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

## Linear regression model - Assumptions

In [19]:
import numpy as np
import pandas as pd
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt
import seaborn as sns